import { createChunks, diagnosisLabels, guidedScenarios, runBusinessCase, searchResearch, type LabDocument, type LabRun } from './guided-lab';
import type { LabKey } from './lab-evidence';
import { verticalAppDocument } from './vertical-app';
const safeJson = (value: unknown) => JSON.stringify(value).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
const escapeText = (value: string) => value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!));
export function guidedAppDocument(key: LabKey, documents: LabDocument[], run: LabRun) {
  if (key !== 'rag') return verticalAppDocument(key, {
    records: documents.filter(doc => doc.status === 'ready' && doc.record).map(doc => doc.record!),
    cases: run.rows.map(row => ({ id: row.id, input: row.input, expected: row.expected })),
  }, 'bounded', run, `guided-${key}-${run.signature}`, run.config);
  const title = guidedScenarios.find(item => item.key === key)!.result;
  return String.raw`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeText(title)}</title><style>
  *{box-sizing:border-box}body{margin:0;background:#f5f6f8;color:#202632;font:16px/1.7 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:32px}header{display:flex;justify-content:space-between;align-items:center;gap:20px}h1{font-size:26px;margin:0}small{color:#626b7c}button,select,textarea{font:inherit;border:1px solid #d6dbe4;border-radius:6px;background:white;padding:10px}button{cursor:pointer}button.primary{background:#453791;color:white;border:0}textarea{width:100%;min-height:100px;margin:20px 0 10px}nav{display:flex;gap:12px;align-items:center;margin:16px 0}select{max-width:100%}article{background:#fff;padding:24px;border:1px solid #dce0e8;border-radius:8px;margin:20px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}aside{border-top:1px solid #dce0e8;margin-top:26px;padding-top:16px}details{margin:16px 0}summary{cursor:pointer}#answer h2{font-size:20px}#answer button{color:#453791;text-align:left}p{margin:8px 0}@media(max-width:650px){main{padding:16px}header,nav{align-items:start;flex-direction:column}}
  </style><main><header><div><small>PAW · 离线应用</small><h1>${escapeText(title)}</h1></div><button id="download">下载当前结果</button></header><p><small>${documents.filter(doc => doc.status === 'ready').length} 份资料 · ${escapeText(run.name)} · 检查题通过 ${run.passed}/${run.total}</small></p><nav><label for="examples">${key === 'rag' ? '实验问题' : key === 'cloudops' ? '选择告警' : key === 'enterpriseops' ? '选择客户' : '选择输入记录'}</label><select id="examples"><option value="">${key === 'rag' ? '选择已测评的问题' : '选择已测评的记录'}</option></select></nav><textarea ${key === 'rag' ? '' : 'hidden'} id="input" aria-label="${key === 'rag' ? '研究问题' : '记录编号'}" placeholder="${key === 'rag' ? '输入研究问题，检索原始资料…' : '选择一条记录或输入记录编号…'}"></textarea><button id="run" class="primary">${key === 'rag' ? '查找研究证据' : key === 'cloudops' ? '诊断所选告警' : key === 'enterpriseops' ? '生成交接建议' : '整理所选记录'}</button><section id="answer" aria-live="polite"></section><aside><small>${key === 'rag' ? '在浏览器内执行本地词法检索，输出原文摘录与来源；不生成新的模型研究报告。' : '在浏览器内执行已测评的规则，业务操作只作用于演示数据。'} 此页面无需后端。配置与检查结果随应用保存。</small><details><summary>查看采用的参数与检查结果</summary><pre id="receipt"></pre></details></aside></main><script>
  const search=${searchResearch.toString()};const business=${runBusinessCase.toString()};
  const data=${safeJson({ key, documents, diagnosisLabels, config: run.config, chunks: key === 'rag' ? createChunks(documents, run.config) : [], run })};
  const input=document.getElementById('input'),answer=document.getElementById('answer'),examples=document.getElementById('examples');
  for(const row of data.run.rows){const option=document.createElement('option');option.value=row.id;option.textContent=(data.key==='rag'?row.input:data.documents.find(doc=>doc.id===row.input)?.title||row.input).slice(0,130);examples.append(option)}
  let current=''; document.getElementById('receipt').textContent=JSON.stringify({configuration:data.config,checks:{passed:data.run.passed,total:data.run.total},rows:data.run.rows.map(({id,input,actual,expected,passed})=>({id,input,actual,expected,passed}))},null,2);
  examples.onchange=()=>{input.value=data.run.rows.find(row=>row.id===examples.value)?.input||''};
  const node=(tag,text)=>{const element=document.createElement(tag);element.textContent=text;return element};
  document.getElementById('run').onclick=()=>{answer.replaceChildren();if(!input.value.trim())return;const article=document.createElement('article');
    if(data.key==='rag'){const hits=search(data.chunks,input.value,data.config);article.append(node('h2',hits.length?'研究证据':'未找到相关资料'));current=input.value+'\n\n';
      for(const hit of hits){const section=document.createElement('section');const button=node('button',hit.title);button.onclick=()=>{const doc=data.documents.find(doc=>doc.id===hit.sourceId);const details=document.createElement('details');details.open=true;details.append(node('summary',doc.name),node('pre',doc.text));section.append(details);button.disabled=true};section.append(button,node('pre',hit.text));article.append(section);current+='['+hit.title+']\n'+hit.text+'\n\n'}
      if(!hits.length)article.append(node('p','请补充资料或换一个问题。'));
    }else{const result=business(data.key,data.documents,input.value,data.config);current=result.value+'\n'+result.detail;const title=node('h2',data.key==='cloudops'?data.diagnosisLabels[result.value]||result.value:result.value);title.dataset.value=result.value;article.append(title,node('pre',result.detail))}answer.append(article)};
  document.getElementById('download').onclick=()=>{if(!current)return;const url=URL.createObjectURL(new Blob([current],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='result.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  </script></html>`;
}
